stages:
  - build
  - test

image: rust:1.46.0-alpine3.11

build-rust-latest:
  stage: build
  script:
    - cargo build --verbose

test-rust-latest:
  stage: test
  script:
    - rustc --version && cargo --version
    - cargo test --verbose
  allow_failure: true
