stages:
  - build
  - test

image: rust:latest

build-rust-latest:
  stage: build
  script:
    - cargo build --verbose

test-rust-latest:
  stage: test
  script:
    - cargo test --verbose
  allow_failure: true
