stages:
  - build
  - test

image: rust:latest

pull_policy: if-not-present

build:
  stage: build
  script:
    - cargo build --verbose

test:
  stage: test
  script:
    - cargo test --verbose
  allow_failure: true
