stages:
  - build
  - test

build-rust-latest:
  stage: build
  image: rust:latest
  script:
    - cargo build --verbose

test-rust-latest:
  stage: test
  image: rust:latest
  script:
    - cargo test --verbose
