/// This submodule contains `Body` level node specifications.

  
/// ### BodyNode
/// The set of `Body` level node structs enclosed
/// in an enum. 
pub enum BodyNode {
  Paragraph {},
  Compound {},
  Container {},
  BulletList {},
  EnumeratedList {},
  ListItem {},
  DefinitionList {},
  DefinitionListItem {},
  Term {},
  Classifier {},
  Definition {},
  FieldList {},
  Field {},
  FieldName {},
  FieldBody {},
  Option {},
  OptionArgument {},
  OptionGroup {},
  OptionList {},
  OptionListItem {},
  OptionString {},
  Description {},
  LiteralBlock {},
  DoctestBlock {},
  MathBlock {},
  LineBlock {},
  Line {},
  BlockQuote {},
  Attribution {},
  Attention {},
  Caution {},
  Danger {},
  Error {},
  Important {},
  Note {},
  Tip {},
  Hint {},
  Warning {},
  Admonition {},
  Comment {},
  SubsstitutionDefinition {},
  Target {},
  Footnote {},
  Citation {},
  Label {},
  Figure {},
  Caption {},
  Legend {},
  Table {},
  TableGroup {},
  ColSpec {},
  TableHead {},
  TableBody {},
  TableRow {},
  TableEntry {},
}
